title: MLMI Notes
description: Antonio Franca's notes for the MPhil in Machine Learning and Machine Intelligence
author: Antonio Franca
theme: jekyll-theme-cayman
markdown: kramdown

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
